name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Azure CLI
      uses: azure/CLI@v2  # Updated to the latest version

    - name: Login to Azure
      uses: azure/login@v2  # Updated to the latest version
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      run: |
        az deployment group create \
          --resource-group $RESOURCE_GROUP \
          --template-file ./infra/main.bicep
