name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Azure CLI
      uses: azure/CLI@v2  # Updated to the latest version

    - name: Login to Azure
      uses: azure/login@v2  # Updated to the latest version
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM template
      run: |
        for dir in infra/*; do
          az deployment group create \
            --resource-group $(basename $dir) \
            --template-file $dir/arm-template.json
        done
