name: GitOps Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Azure CLI
        uses: azure/setup-cli@v1

      - name: Login to Azure
        run: az login --service-principal -u $AZURE_SERVICE_PRINCIPAL_NAME -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant $AZURE_TENANT_ID

      - name: Deploy Bicep files
        run: az deployment group create --resource-group <your-resource-group> --template-file ././bicep/vm-deployment.bicep --parameters vmName='<your-vm-name>' adminUsername='<your-admin-username>' adminPassword='<your-admin-password>'
