name: GitOps Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy all Bicep files
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            for bicepFile in ./bicep/*.bicep; do
              echo "Deploying $bicepFile"
              az deployment group create --resource-group <your-resource-group> --template-file "$bicepFile"
            done
